import './globals.css'
import { Header } from '@/components/header'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { DefaultProviders } from '@/components/default-providers'

const jakarta = Plus_Jakarta_Sans({ 
  weight:['200','300', '400','500', '600', '700', '800'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Leadster',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <DefaultProviders>
          <Header/>
          {children}
         </DefaultProviders>
      </body>
    </html>
  )
}
